// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"

///////////////////// VARIABLES ////////////////////
//static rt_thread_t xinzhi_weather_thread;

static lv_obj_t *ui_Screen1;
static lv_obj_t *github;
static lv_obj_t *ui____initial_actions0;
static lv_obj_t *electric_num;
static lv_obj_t *electric_img;
static lv_obj_t *weather;
static lv_obj_t *weather_describe;
static lv_obj_t *temperature;
static lv_obj_t *temperature_num;
static lv_obj_t *successed_wifi_img;
static lv_obj_t *unsuccessed_wifi_img;
static lv_obj_t *time_minute;
static lv_obj_t *time_sketchy;
static lv_obj_t *gas_img;
static lv_obj_t *cat_img;
///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
// #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP !=1
// #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

LV_FONT_DECLARE(normal_myfont);
LV_FONT_DECLARE(small_myfont);
LV_FONT_DECLARE(electric);
LV_FONT_DECLARE(wifi_successed);
LV_FONT_DECLARE(wifi_unsuccessed);
LV_FONT_DECLARE(gas);
LV_FONT_DECLARE(sleepy_cat);

void set_wifi_status(int flag)
{
    if (flag == HAVE_WIFI)
    {
        lv_img_set_zoom(successed_wifi_img, 38);
        lv_img_set_zoom(unsuccessed_wifi_img, 0);
    }
    else
    {
        lv_img_set_zoom(unsuccessed_wifi_img, 38);
        lv_img_set_zoom(successed_wifi_img, 0);
    }

}

char* nub_to_string(int num)
{
    char* target = (char*) malloc(sizeof(char) * 20);

    char show_num[5] = "0000";

    int temp = num;
    int i = 0;
    for (; temp != 0; temp /= 10)
        i++;
    show_num[i] = '\0';
    int size = i + 1;

    for (i = i - 1; i >= 0; num /= 10, i--)
        show_num[i] = num % 10 + '0';

    for (int i = 0; i != size; i++)
        *(target + i) = show_num[i];

    return target;
}

void set_electric_num(int num)
{
    if (num > 100)
        num = 100;
    char show_num[5] = "0000";

    int temp = num;
    int i = 0;
    for (; temp != 0; temp /= 10)
        i++;
    show_num[i] = num == 100 ? '\0' : '%';

    show_num[i + 1] = '\0';

    for (i = i - 1; i >= 0; num /= 10, i--)
        show_num[i] = num % 10 + '0';

    lv_label_set_text(electric_num, show_num);
    return;
}

void set_temperature_num(int integer, int decimals)
{

    lv_label_set_text(temperature_num, nub_to_string(integer));
    lv_label_ins_text(temperature_num, LV_LABEL_POS_LAST, ".");
    lv_label_ins_text(temperature_num, LV_LABEL_POS_LAST, nub_to_string(decimals));
    return;
}

void Chinese_character_Show(void)
{

    github = lv_label_create(ui_Screen1, NULL);
    lv_obj_set_style_local_text_font(github, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &small_myfont);
    lv_label_set_long_mode(github, LV_LABEL_LONG_SROLL_CIRC);
    lv_label_set_text(github, "项目源码地址:https://github.com/KurisaW-Collaborative/EC_Project/     ");
    lv_obj_set_width(github, 450);  /// 1
    //lv_obj_set_height(label, 10); /// 1
    lv_obj_set_x(github, 0);
    lv_obj_set_y(github, 0);

    weather = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(weather, true);
    lv_obj_set_style_local_text_font(weather, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(weather, 200);  /// 1
    lv_obj_set_height(weather, 150); /// 1
    lv_obj_set_x(weather, 0);
    lv_obj_set_y(weather, 40);
    lv_label_set_text(weather, "#0000ff 天气: #");

    temperature = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(temperature, true);
    lv_obj_set_style_local_text_font(temperature, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(temperature, 200);  /// 1
    lv_obj_set_height(temperature, 150); /// 1
    lv_obj_set_x(temperature, 0);
    lv_obj_set_y(temperature, 60);
    lv_label_set_text(temperature, "#0000ff 温度: #");

    //图片
    electric_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(electric_img, &electric);
    lv_img_set_zoom(electric_img, 38);
    lv_obj_set_x(electric_img, 423);
    lv_obj_set_y(electric_img, 16);
    lv_img_set_pivot(electric_img, 0, 0); /*Rotate around the top left corner*/

    gas_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(gas_img, &gas);
    lv_img_set_zoom(gas_img, 100);
    lv_obj_set_x(gas_img, 380);
    lv_obj_set_y(gas_img, 100);
    lv_img_set_pivot(gas_img, 0, 0); /*Rotate around the top left corner*/

    cat_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(cat_img, &sleepy_cat);
    lv_img_set_zoom(cat_img, 200);
    lv_obj_set_x(cat_img, 0);
    lv_obj_set_y(cat_img, 100);
    lv_img_set_pivot(cat_img, 0, 0); /*Rotate around the top left corner*/

    unsuccessed_wifi_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(unsuccessed_wifi_img, &wifi_unsuccessed);
    lv_img_set_zoom(unsuccessed_wifi_img, 38);
    lv_obj_set_x(unsuccessed_wifi_img, 380);
    lv_obj_set_y(unsuccessed_wifi_img, 16);
    lv_img_set_pivot(unsuccessed_wifi_img, 0, 0); /*Rotate around the top left corner*/

    successed_wifi_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(successed_wifi_img, &wifi_successed);
    lv_img_set_zoom(successed_wifi_img, 38);
    lv_obj_set_x(successed_wifi_img, 380);
    lv_obj_set_y(successed_wifi_img, 16);
    lv_img_set_pivot(successed_wifi_img, 0, 0); /*Rotate around the top left corner*/

    lv_img_set_zoom(successed_wifi_img, 0);

    electric_num = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(electric_num, true);
    lv_obj_set_style_local_text_font(electric_num, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(electric_num, 200);  /// 1
    lv_obj_set_height(electric_num, 150); /// 1
    lv_obj_set_x(electric_num, 426);
    lv_obj_set_y(electric_num, 20);
    set_electric_num(100);

    weather_describe = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(weather_describe, true);
    lv_obj_set_style_local_text_font(weather_describe, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(weather_describe, 200);  /// 1
    lv_obj_set_height(weather_describe, 150); /// 1
    lv_obj_set_x(weather_describe, 48);
    lv_obj_set_y(weather_describe, 40);
    lv_label_set_text(weather_describe, "获取中");

    temperature_num = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(temperature_num, true);
    lv_obj_set_style_local_text_font(temperature_num, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(temperature_num, 200);  /// 1
    lv_obj_set_height(temperature_num, 150); /// 1
    lv_obj_set_x(temperature_num, 48);
    lv_obj_set_y(temperature_num, 60);
    set_temperature_num(10, 2);

    time_minute = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(time_minute, true);
    lv_obj_set_style_local_text_font(time_minute, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(time_minute, 200);  /// 1
    lv_obj_set_height(time_minute, 150); /// 1
    lv_obj_set_x(time_minute, 200);
    lv_obj_set_y(time_minute, 20);

    time_sketchy = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(time_sketchy, true);
    lv_obj_set_style_local_text_font(time_sketchy, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_myfont);
    lv_obj_set_width(time_sketchy, 200);  /// 1
    lv_obj_set_height(time_sketchy, 150); /// 1
    lv_obj_set_x(time_sketchy, 0);
    lv_obj_set_y(time_sketchy, 20);

}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL, NULL);

    Chinese_character_Show();
}

#define GET_HEADER_BUFSZ               1024
#define GET_RESP_BUFSZ                 1024

static int webclient_get_comm(const char *uri)
{

    struct webclient_session* session = RT_NULL;
    char *buffer = RT_NULL;
    int index, ret = 0;
    int bytes_read, resp_status;
    int content_length = -1;

    buffer = (char *) web_malloc(GET_RESP_BUFSZ);
    if (buffer == RT_NULL)
    {
        rt_kprintf("no memory for receive buffer.\n");
        ret = -RT_ENOMEM;
        goto __exit;

    }

    /* create webclient session and set header response size */
    session = webclient_session_create(GET_HEADER_BUFSZ);
    if (session == RT_NULL)
    {
        ret = -RT_ENOMEM;
        goto __exit;
    }

    /* send GET request by default header */
    if ((resp_status = webclient_get(session, uri)) != 200)
    {
        rt_kprintf("webclient GET request failed, response(%d) error.\n", resp_status);
        ret = -RT_ERROR;
        goto __exit;
    }

    rt_kprintf("webclient get response data: \n");

    content_length = webclient_content_length_get(session);
    if (content_length < 0)
    {
        rt_kprintf("webclient GET request type is chunked.\n");
        do
        {
            bytes_read = webclient_read(session, (void *) buffer, GET_RESP_BUFSZ);
            if (bytes_read <= 0)
            {
                break;
            }

            for (index = 0; index < bytes_read; index++)
            {
                rt_kprintf("%c", buffer[index]);
            }
        } while (1);

        rt_kprintf("\n");
    }
    else
    {
        int content_pos = 0;

        do
        {
            bytes_read = webclient_read(session, (void *) buffer,
                    content_length - content_pos > GET_RESP_BUFSZ ?
                    GET_RESP_BUFSZ :
                                                                    content_length - content_pos);
            if (bytes_read <= 0)
            {
                break;
            }
            content_pos += bytes_read;
        } while (content_pos < content_length);

        rt_kprintf("\n");
    }

    cJSON* weather_json = cJSON_Parse(buffer);
    if (weather_json == NULL)                       //判断转换是否成功
    {
        rt_kprintf("cjson error...\r\n");
    }
    cJSON* weather_results = cJSON_GetObjectItem(weather_json, "results");
    // 获取数组中的第一个对象  注意他返回的时候results下面的第一级是个数组 所以要先取出数组元素
    cJSON* firstObj = cJSON_GetArrayItem(weather_results, 0);

    cJSON* weather_now = cJSON_GetObjectItem(firstObj, "now");

    char* wather_chinese_description = cJSON_GetObjectItem(weather_now, "text")->valuestring;   //解析对象中的字符串
    lv_label_set_text(weather_describe, wather_chinese_description);

    cJSON_Delete(weather_json);   //清除结构体

    __exit: if (session)
    {
        webclient_close(session);
    }

    if (buffer)
    {
        web_free(buffer);
    }

    return ret;
}

void xinzhi_weather_thread_entry()
{
    while (1)
    {

        char *uri = RT_NULL;
        uri =
                web_strdup(
                        "http://api.seniverse.com/v3/weather/now.json?key=ShDCbS5wypAchCMIi&location=哈尔滨&language=zh-Hans&unit=c&days=1");
        if (uri == RT_NULL)
        {
            rt_kprintf("no memory for create get request uri buffer.\n");
            return;
        }
        webclient_get_comm(uri);

        if (uri)
        {
            web_free(uri);
        }
        rt_thread_mdelay(10000);
    }
}

void refresh_thread_entry()
{

    while (1)
    {
#define EVENT_FLAG3 (1 << 3)
        while (RT_EOK != rt_event_recv(&wifi_event, EVENT_FLAG3, RT_EVENT_FLAG_OR, 1000, NULL))
            set_wifi_status(NO_HAVE_WIFI);
        set_wifi_status(HAVE_WIFI);
        ntp_sync_to_rtc(RT_NULL);   //获取当前的 UTC 时间，并更新至 RTC（实时时钟）中。

        //显示时间
        time_t timep;
        struct tm *tm;

        time(&timep);
        tm = localtime(&timep);

        if (tm->tm_hour < 10 && tm->tm_hour > 0)
        {
            lv_label_set_text(time_minute, "0");
            lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, nub_to_string(tm->tm_min));
        }
        else
            lv_label_set_text(time_minute, nub_to_string(tm->tm_hour));
        if (!tm->tm_hour)
            lv_label_set_text(time_minute, "00");

        lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, ":");
        if (tm->tm_min < 10 && tm->tm_min > 0)
            lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, "0");
        lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, nub_to_string(tm->tm_min));
        if (!tm->tm_min)
            lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, "00");

        lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, ":");
        if (tm->tm_sec < 10 && tm->tm_sec > 0)
            lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, "0");
        lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, nub_to_string(tm->tm_sec));
        if (!tm->tm_sec)
            lv_label_ins_text(time_minute, LV_LABEL_POS_LAST, "00");

        lv_label_set_text(time_sketchy, "星期");

        //使用字符串通过下标访问会出现一些莫名其妙的bug 选择使用switch方式
        switch (tm->tm_wday)
        {
        case 1:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "一");
            break;
        case 2:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "二");
            break;
        case 3:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "三");
            break;
        case 4:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "四");
            break;
        case 5:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "五");
            break;
        case 6:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "六");
            break;
        case 7:
            lv_label_ins_text(time_sketchy, LV_LABEL_POS_LAST, "日");
            break;
        }
        rt_thread_mdelay(900);
    }
}

extern ui_Screen2_screen_init();
extern ui_Screen3_screen_init();

void ui_init(void)
{

    littlevgl2rtt_init("lcd");

    lv_disp_t *dispp = lv_disp_get_default();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL, NULL);
    lv_disp_load_scr(ui_Screen1);

    rt_thread_t refresh_thread = rt_thread_create("refresh_thread", refresh_thread_entry, RT_NULL, 4096, 10, 10);
    // 启动线程
    if (refresh_thread != RT_NULL)
        rt_thread_startup(refresh_thread);
    else
        rt_kprintf("refresh_thread startup error \n");

    rt_thread_t xinzhi_weather_thread = rt_thread_create("xinzhi_weather_thread", xinzhi_weather_thread_entry, RT_NULL,
            4096, 10, 10);
    // 启动线程
    while (RT_EOK != rt_event_recv(&wifi_event, EVENT_FLAG3, RT_EVENT_FLAG_OR, 1000, NULL))
        ;
    if (xinzhi_weather_thread != RT_NULL)
        rt_thread_startup(xinzhi_weather_thread);
    else
        rt_kprintf("xinzhi_weather_thread_entry startup error \n");

}

void show_main_screen()
{
    lv_disp_load_scr(ui_Screen1);
}
