// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <rtthread.h>
#include "lvgl.h"
#include "rtdef.h"
#include <webclient.h>
#include "ntp.h"
#include <cJSON.h>
#include <time.h>
//extern lv_obj_t *ui_Screen1;
//extern lv_obj_t *ui_Label2;
//extern lv_obj_t *ui_Label1;
//extern lv_obj_t *ui_Label4;
//extern lv_obj_t *ui____initial_actions0;

extern struct rt_event wifi_event;

enum wifi_status{
  NO_HAVE_WIFI = 0,
  HAVE_WIFI ,
};


void ui_init(void);
void set_electric_num(int num);
void set_wifi_status(int flag);
void set_temperature_num(int integer,int decimals);
void show_error_screen();
void show_warning_screen();
void show_main_screen();

void set_error_info(char* error_message);
void set_warning_info(char* warning_message);

void xinzhitest();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
