// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project
#include <rtthread.h>
#include "ui.h"

///////////////////// VARIABLES ////////////////////
//static rt_thread_t xinzhi_weather_thread;

static lv_obj_t *ui_Screen1;
static lv_obj_t *github;
static lv_obj_t *ui____initial_actions0;
static lv_obj_t *electric_num;
static lv_obj_t *electric_img;
static lv_obj_t *weather;
static lv_obj_t *city;
static lv_obj_t *temperature;
static lv_obj_t *pressure;
static lv_obj_t *humidity;
static lv_obj_t *successed_wifi_img;
static lv_obj_t *unsuccessed_wifi_img;
static lv_obj_t *time_minute;
static lv_obj_t *time_sketchy;
static lv_obj_t *gas_img;
static lv_obj_t *cat_img;

static rt_timer_t timer1;//绠＄悊鏃堕棿鏄剧ず

static rt_thread_t refresh_thread;
static bool lvgl_use = 0;
///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
// #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP !=1
// #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

LV_FONT_DECLARE(normal_font);
LV_FONT_DECLARE(small_font);
LV_FONT_DECLARE(electric);
LV_FONT_DECLARE(wifi_successed);
LV_FONT_DECLARE(wifi_unsuccessed);
LV_FONT_DECLARE(gas);
LV_FONT_DECLARE(sleepy_cat);
LV_FONT_DECLARE(main_ui_background);

void set_wifi_status(int flag)
{
    if (flag == HAVE_WIFI)
    {
        lv_img_set_zoom(successed_wifi_img, 38);
        lv_img_set_zoom(unsuccessed_wifi_img, 0);
    }
    else
    {
        lv_img_set_zoom(unsuccessed_wifi_img, 38);
        lv_img_set_zoom(successed_wifi_img, 0);
    }

}

static char* nub_to_string(int num)
{
    char* target = (char*) malloc(sizeof(char) * 20);

    char show_num[5] = "0000";

    int temp = num;
    int i = 0;
    for (; temp != 0; temp /= 10)
        i++;
    show_num[i] = '\0';
    int size = i + 1;

    for (i = i - 1; i >= 0; num /= 10, i--)
        show_num[i] = num % 10 + '0';

    for (int i = 0; i != size; i++)
        *(target + i) = show_num[i];

    return target;
}

void set_electric_num(int num)
{
    if (num > 100)
        num = 100;
    char show_num[5] = "0000";

    int temp = num;
    int i = 0;
    for (; temp != 0; temp /= 10)
        i++;
    show_num[i] = num == 100 ? '\0' : '%';

    show_num[i + 1] = '\0';

    for (i = i - 1; i >= 0; num /= 10, i--)
        show_num[i] = num % 10 + '0';

    lv_label_set_text(electric_num, show_num);
    return;
}

static int g_hour;
static int g_points;
static int g_seconds;
static int g_wday = 1;

void set_time(int hour,int points,int seconds,int wday)
{

    if (timer1 != RT_NULL) rt_timer_stop(timer1);

    if(hour >= 0 && hour <= 24) g_hour = hour ;
    if(points >= 0 && points <=60) g_points = points;
    if(seconds >= 0 && seconds <= 60) g_seconds = seconds;
    if(wday > 0 && g_wday <= 7) g_wday = wday;



    if (timer1 != RT_NULL) rt_timer_start(timer1);
}

void set_temperature(char* num)
{

    lv_label_set_text(temperature, "#0000ff Temperature: #");
    lv_label_ins_text(temperature, LV_LABEL_POS_LAST, num);
    return;
}

void set_pressure(char* pressure_num)
{
    lv_label_set_text(pressure, "#0000ff Pressure: #");
    lv_label_ins_text(pressure, LV_LABEL_POS_LAST, pressure_num);
}

void set_humidity(char* humidity_num)
{
    lv_label_set_text(humidity, "#0000ff Humidity: #");
    lv_label_ins_text(humidity, LV_LABEL_POS_LAST, humidity_num);
}

void set_city(char * city_name)
{
    lv_label_set_text(city, "#0000ff City: #");
    lv_label_ins_text(city, LV_LABEL_POS_LAST, city_name);
    return;
}

static void set_weather_describe(char * weather_describe)
{
    lv_label_set_text(weather, "#0000ff Weather: #");
    lv_label_ins_text(weather, LV_LABEL_POS_LAST, weather_describe);
}



static void Chinese_character_Show(void)
{

    github = lv_label_create(ui_Screen1, NULL);
    lv_obj_set_style_local_text_font(github, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &small_font);
    lv_label_set_long_mode(github, LV_LABEL_LONG_SROLL_CIRC);
    lv_label_set_text(github, "Project code:https://github.com/KurisaW-Collaborative/EC_Project/     ");
    lv_obj_set_width(github, 450);
    lv_obj_set_x(github, 0);
    lv_obj_set_y(github, 0);
//娑撴槒顩︾�涙顑�
    city = lv_label_create(ui_Screen1, NULL);
         lv_label_set_recolor(city, true);
         lv_obj_set_style_local_text_font(city, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
         lv_obj_set_x(city, 0);
        lv_obj_set_y(city, 42);
        set_city("Harbin");

    weather = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(weather, true);
    lv_obj_set_style_local_text_font(weather, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
    lv_obj_set_width(weather, 200);  /// 1
    lv_obj_set_height(weather, 150); /// 1
    lv_obj_set_x(weather, 0);
    lv_obj_set_y(weather, 62);
    set_weather_describe("Acquiring...");

    temperature = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(temperature, true);
    lv_obj_set_style_local_text_font(temperature, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
    lv_obj_set_width(temperature, 200);  /// 1
    lv_obj_set_height(temperature, 150); /// 1
    lv_obj_set_x(temperature, 0);
    lv_obj_set_y(temperature, 82);
    set_temperature("13.5");

    humidity = lv_label_create(ui_Screen1, NULL);
        lv_label_set_recolor(humidity, true);
        lv_obj_set_style_local_text_font(humidity, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
        lv_obj_set_width(humidity, 200);  /// 1
        lv_obj_set_height(humidity, 150); /// 1
        lv_obj_set_x(humidity, 0);
        lv_obj_set_y(humidity, 102);
        set_humidity("19.25");

        pressure = lv_label_create(ui_Screen1, NULL);
        lv_label_set_recolor(pressure, true);
        lv_obj_set_style_local_text_font(pressure, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
        lv_obj_set_width(pressure, 200);  /// 1
        lv_obj_set_height(pressure, 150); /// 1
        lv_obj_set_x(pressure, 0);
        lv_obj_set_y(pressure, 122);
        set_pressure("18.5");
    //閸ュ墽澧�
    electric_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(electric_img, &electric);
    lv_img_set_zoom(electric_img, 38);
    lv_obj_set_x(electric_img, 320-57);
    lv_obj_set_y(electric_img, 16);
    lv_img_set_pivot(electric_img, 0, 0); /*Rotate around the top left corner*/

    gas_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(gas_img, &gas);
    lv_img_set_zoom(gas_img, 100);
    lv_obj_set_x(gas_img, 380);
    lv_obj_set_y(gas_img, 100);
    lv_img_set_pivot(gas_img, 0, 0); /*Rotate around the top left corner*/

    cat_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(cat_img, &sleepy_cat);
    lv_img_set_zoom(cat_img, 200);
    lv_obj_set_x(cat_img, 0);
    lv_obj_set_y(cat_img, 100+20);
    lv_img_set_pivot(cat_img, 0, 0); /*Rotate around the top left corner*/

    unsuccessed_wifi_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(unsuccessed_wifi_img, &wifi_unsuccessed);
    lv_img_set_zoom(unsuccessed_wifi_img, 38);
    lv_obj_set_x(unsuccessed_wifi_img, 220);
    lv_obj_set_y(unsuccessed_wifi_img, 16);
    lv_img_set_pivot(unsuccessed_wifi_img, 0, 0); /*Rotate around the top left corner*/

    successed_wifi_img = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(successed_wifi_img, &wifi_successed);
    lv_img_set_zoom(successed_wifi_img, 38);
    lv_obj_set_x(successed_wifi_img, 220);
    lv_obj_set_y(successed_wifi_img, 16);
    lv_img_set_pivot(successed_wifi_img, 0, 0); /*Rotate around the top left corner*/

    lv_img_set_zoom(successed_wifi_img, 0);
//閸忔湹绮�
    electric_num = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(electric_num, true);
    lv_obj_set_style_local_text_font(electric_num, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
    lv_obj_set_x(electric_num, 320-54);
    lv_obj_set_y(electric_num, 20);
    set_electric_num(100);

    time_minute = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(time_minute, true);
    lv_obj_set_style_local_text_font(time_minute, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
    lv_obj_set_x(time_minute, 120);
    lv_obj_set_y(time_minute, 20);

    time_sketchy = lv_label_create(ui_Screen1, NULL);
    lv_label_set_recolor(time_sketchy, true);
    lv_obj_set_style_local_text_font(time_sketchy, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &normal_font);
    lv_obj_set_x(time_sketchy, 0);
    lv_obj_set_y(time_sketchy, 20);

}

static void ui_screen_main_init(void)
{
    ui_Screen1 = lv_obj_create(NULL, NULL);

    lv_obj_t *background = lv_img_create(ui_Screen1, NULL);
    lv_img_set_src(background, &main_ui_background);
    lv_img_set_zoom(background,545);
    lv_obj_set_width(background, 480);
    lv_obj_set_height(background, 320);

    lv_obj_set_x(background, 0);
    lv_obj_set_y(background, 0);
    lv_img_set_pivot(background, 0, 0); /*Rotate around the top left corner*/

    Chinese_character_Show();
}

#define GET_HEADER_BUFSZ               1024
#define GET_RESP_BUFSZ                 1024

/* 软件定时器用于时钟时间显示 */
static void timeout1(void *parameter)
{
    int carry = 0;

    g_seconds++;
    carry = g_seconds / 60;
    if(carry == 0 ) return;
    g_seconds %= 60;

    g_points = g_points + carry;
    carry = g_points /60;
    if(carry == 0 ) return;
    g_points %= 60;

    g_hour = g_hour + carry;
    carry = g_hour /24;
    if(carry == 0 ) return;
    g_points %= 24;

    g_wday = g_wday + carry;
    g_points %= 7;

}

static int get_random_number(float minData, float maxData)
{
    srand(rt_tick_get());

    float random = (float)rand() / RAND_MAX;

    float rand_data_range = maxData - minData;
    float result_rand_data = (random * rand_data_range) + minData;

    return (int)result_rand_data;
}

static void float_to_str(int integer,int decimals,char* ss)
{
    if(decimals == 0) snprintf(ss,20,"%d",integer);
    else snprintf(ss,20,"%d.%d",integer,decimals);
}


static void refresh_thread_entry()
{

    if (timer1 == RT_NULL)
    {
        timer1 = rt_timer_create("timer1", timeout1,
        RT_NULL, RT_TICK_PER_SECOND ,
        RT_TIMER_FLAG_PERIODIC);

        if (timer1 != RT_NULL)
            rt_timer_start(timer1);
    }

    while (lvgl_use)
    {
        //閺勫墽銇氶弮鍫曟？
//        time_t timep;
//        struct tm *tm;
//
//        time(&timep);
//        tm = localtime(&timep);

#if 1
        //设置温度
        int integer = 20;
        int decimals = get_random_number(1,10);
        char t_temp[20];
        rt_memset(t_temp, 0, sizeof(t_temp));
        float_to_str(integer,decimals,t_temp);

        set_deteciton_temperature(t_temp);
        set_deteciton_abnormal_temperature(t_temp);
        set_temperature(t_temp);


        //设置湿度
        integer = 98;
        decimals = get_random_number(89,91);
        rt_memset(t_temp, 0, sizeof(t_temp));
        float_to_str(integer,decimals,t_temp);
        set_humidity(t_temp);
        set_deteciton_humidity(t_temp);
        set_deteciton_abnormal_humidity(t_temp);

        //设置气压
        integer = get_random_number(980,990);
        rt_memset(t_temp, 0, sizeof(t_temp));
        snprintf(t_temp,20,"%dhpa",integer);
        set_pressure(t_temp);
        set_deteciton_abnormal_pressure(t_temp);
        set_deteciton_pressure(t_temp);

        integer = get_random_number(600,800);
        rt_memset(t_temp, 0, sizeof(t_temp));
        float_to_str(integer,0,t_temp);
        set_deteciton_abnormal_illumination(t_temp);
        set_deteciton_illumination(t_temp);

        set_electric_num(100);

        set_speed("1.8km/h");
        set_direction("due north");
        set_travel_time("0.1h");
        set_travel_distance("20");

#endif

        if (g_hour < 10 && g_hour > 0)
        {
            lv_label_set_text( now_show_ui.time_minute, "0");
            lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, nub_to_string(g_points));
        }
        else
            lv_label_set_text( now_show_ui.time_minute, nub_to_string(g_hour));
        if (!g_hour)
            lv_label_set_text( now_show_ui.time_minute, "00");

        lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, ":");
        if (g_points < 10 && g_points > 0)
            lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, "0");
        lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, nub_to_string(g_points));
        if (!g_points)
            lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, "00");

        lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, ":");
        if (g_seconds < 10 && g_seconds > 0)
            lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, "0");
        lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, nub_to_string(g_seconds));
        if (!g_seconds)
            lv_label_ins_text( now_show_ui.time_minute, LV_LABEL_POS_LAST, "00");


        //閸樼喎鍘涙担璺ㄦ暏鐎涙顑佹稉鏌ワ拷姘崇箖娑撳鐖ｇ拋鍧楁６娑擃厽鏋冩导姘毉閻滈绔存禍娑滃缚閸氬秴鍙炬俊娆戞畱bug 闁瀚ㄦ担璺ㄦ暏switch閺傜懓绱�  閻滄澘婀幊鎺戠繁閺�閫涚啊閿涳拷
        switch (g_wday)
        {
        case 0:
                    lv_label_set_text( now_show_ui.time_sketchy, "Sunday");
                    break;
        case 1:
            lv_label_set_text( now_show_ui.time_sketchy, "Monday");
            break;
        case 2:
            lv_label_set_text( now_show_ui.time_sketchy, "Tuesday");
            break;
        case 3:
            lv_label_set_text( now_show_ui.time_sketchy, "Wednesday");
            break;
        case 4:
            lv_label_set_text( now_show_ui.time_sketchy, "Thursday");
            break;
        case 5:
            lv_label_set_text( now_show_ui.time_sketchy, "Friday");
            break;
        case 6:
            lv_label_set_text( now_show_ui.time_sketchy, "Saturday");
            break;
        case 7:
            lv_label_set_text( now_show_ui.time_sketchy, "Sunday");
            break;
        }
        rt_thread_mdelay(900);
    }
}

extern void ui_screen_warning_init();
extern void ui_screen_error_init();
extern void ui_screen_start_init();
extern void ui_screen_kinestate_init();
extern void ui_screen_detection_init();
extern void  detection_data_abnormal_ui_init();

static int fist_init = 1;
void ui_init(void)
{

    lcd_clear(WHITE);
    rt_err_t error = littlevgl2rtt_init("lcd");
    lvgl_use =1;
    if(RT_EOK != error)
    {
        rt_kprintf("littlevgl2rtt_init error");
    }
    dispp = lv_disp_get_default();

    now_show_ui.screen = ui_Screen1;
    now_show_ui.time_minute = time_minute;
    now_show_ui.time_sketchy = time_sketchy;

    if(fist_init)
    {
        ui_screen_start_init();
        ui_screen_main_init();
        ui_screen_warning_init();
        ui_screen_error_init();
        ui_screen_detection_init();
        ui_screen_kinestate_init();
        detection_data_abnormal_ui_init();
        ui____initial_actions0 = lv_obj_create(NULL, NULL);
        fist_init = 0;
    }

    ui_tigger_start();
    //enable_lvgl_rsmg();

    show_start_ui();
 //   lv_disp_load_scr(ui_Screen1);

     refresh_thread = rt_thread_create("refresh_thread", refresh_thread_entry, RT_NULL, 4096, 10, 10);


    if (refresh_thread != RT_NULL)
        rt_thread_startup(refresh_thread);
    else
        rt_kprintf("refresh_thread startup error \n");

//    rt_thread_t xinzhi_weather_thread = rt_thread_create("xinzhi_weather_thread", xinzhi_weather_thread_entry, RT_NULL,
//            4096, 10, 10);
//
//    while (RT_EOK != rt_event_recv(&wifi_event, EVENT_FLAG3, RT_EVENT_FLAG_OR, 1000, NULL));
//
//    if (xinzhi_weather_thread != RT_NULL)
//        rt_thread_startup(xinzhi_weather_thread);
//    else
//        rt_kprintf("xinzhi_weather_thread_entry startup error \n");

}
//INIT_APP_EXPORT(ui_init);
MSH_CMD_EXPORT(ui_init,ui_init);

void close_lvgl_show()
{
    disable_lvgl_rsmg();
    ui_tigger_end();
    lvgl_use = 0;
    littlevgl2rtt_deinit();
    lcd_clear(WHITE);
}
MSH_CMD_EXPORT(close_lvgl_show,close_lvgl_show);

void show_main_ui()
{
    lv_disp_load_scr(ui_Screen1);
    now_show_ui.screen = ui_Screen1;
    now_show_ui.time_minute = time_minute;
    now_show_ui.time_sketchy = time_sketchy;
}
