#ifndef __RT_AI_FIRE_MODEL_H
#define __RT_AI_FIRE_MODEL_H

#include <fire.h>
#include <fire_data.h>

/* model info ... */

// model name
#define RT_AI_FIRE_MODEL_NAME			"fire"
#define RT_AI_FIRE_WORK_BUFFER_BYTES		AI_FIRE_DATA_ACTIVATIONS_SIZE
#define RT_AI_FIRE_DATA_WEIGHTS_SIZE		AI_FIRE_DATA_WEIGHTS_SIZE

#define RT_AI_FIRE_BUFFER_ALIGNMENT		AI_FIRE_ACTIVATIONS_ALIGNMENT

#define RT_AI_FIRE_IN_NUM				AI_FIRE_IN_NUM
#define RT_AI_FIRE_IN_1_SIZE				AI_FIRE_IN_1_SIZE
#define RT_AI_FIRE_IN_1_SIZE_BYTES		AI_FIRE_IN_1_SIZE_BYTES
#define RT_AI_FIRE_IN_TOTAL_SIZE_BYTES	(AI_FIRE_IN_1_SIZE_BYTES)
#define RT_AI_FIRE_IN_SIZE_BYTES			{AI_FIRE_IN_1_SIZE_BYTES}


#define RT_AI_FIRE_OUT_NUM				AI_FIRE_OUT_NUM
#define RT_AI_FIRE_OUT_1_SIZE			AI_FIRE_OUT_1_SIZE
#define RT_AI_FIRE_OUT_1_SIZE_BYTES		AI_FIRE_OUT_1_SIZE_BYTES
#define RT_AI_FIRE_OUT_TOTAL_SIZE_BYTES	(AI_FIRE_OUT_1_SIZE_BYTES)
#define RT_AI_FIRE_OUT_SIZE_BYTES		{AI_FIRE_OUT_1_SIZE_BYTES}


#define RT_AI_FIRE_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
